#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
#  StickMan
#  Copyright (C) 2019 Andrés Segovia
#
#  StickMan is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os
import datetime
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

def show_license():
    dev_year = 2019
    current_year = datetime.date.today().year
    if dev_year != current_year:
        timelapse = f"{dev_year}-{current_year}"
    else:
        timelapse = f"{dev_year}"
    print(
        """
        Copyright (C) {} Andrés Segovia
        This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
        you are welcome to redistribute it under certain conditions. See the GNU
        General Public License for details.
        """.format(timelapse)
    )


def show_version(version):
    print(f"StickMan {version}\n")


def usage():
    print(
        "{}: stickman [OPTION]\n"
        "{}\n\n"
        "{}:\n"
        " -h, --help\t\t{}\n"
        " -v, --version\t\t{}\n"
        " -l, --license\t\t{}\n".format(
            "Usage",
            "Show a toon in your desktop",
            "Options",
            "Display this message and exit.",
            "Print version information.",
            "Show the type of license of this software"))


if __name__ == "__main__":
    sys.path.pop(0)  # Remove the current directory from the list to not import modules
    current_dir = os.getcwd()
    listdir = os.listdir(current_dir)
    if 'data' in listdir and 'src' in listdir:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src")
    else:
        _prefix = os.path.sep + "usr"
        path = os.path.join(_prefix, "share", "stickman")
    sys.path.insert(0, path)

    if len(sys.argv) == 2:
        arg = sys.argv[1]
        if arg in ['-h', '--help']:
            usage()
            sys.exit()
        elif arg in ['-v', '--version']:
            from locals_constants import VERSION
            show_version(version=VERSION)
            sys.exit()
        elif arg in ['-l', '--license']:
            show_license()
            sys.exit()
        elif arg in ['-a', '--about']:
            from widgets import Window, About
            window = Window()
            about = About(window)
            about.run()
            about.destroy()
            sys.exit()
        else:
            print("Incorrect option")
            print("Try \"--help\" to see a list of available command line options")
            sys.exit()
    else:
        from main import main
        gui = main()
        Gtk.main()
